version: '3'
services:
  nginx:
    build: ./proxy
    image: hollomyfoolish/proxy:latest
    external_links:
        - app1
        - app2
    ports:
        - "80:80"
    networks: 
      - default
      - app_net
networks: 
  app_net:
    external: true