version: '3.1'
services:
  app3:
    build: .
    image: hollomyfoolish/app-3004:3
    ports:
      - "3003"
    secrets:
      - db_root_password
      - db_password
    networks: 
      - default
      - app_net  
  app2:
    build: .
    image: hollomyfoolish/node-app:2
    container_name: app2_name
    depends_on:
      - MYapp1
    ports:
      - "3003"
    secrets:
      - db_root_password
      - db_password
    networks: 
      - default
      - app_net
  MYapp1:
    build: .
    image: hollomyfoolish/node-app:1
    # container_name: app1
    depends_on:
      - app-job
    ports:
      - "3003"
    networks: 
      - default
      - app_net
  app-job:
    build: .
    image: hollomyfoolish/node-app:2
    entrypoint: sleep 1m
networks: 
  app_net:
    external: true
secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt