version: '3'
services:
  postgres:
    image: postgres:11-alpine
    environment:
    - POSTGRES_PASSWORD=Initial0
    # :5432
    # network_mode: host
    ports:
    - 127.0.0.1:5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:3.6
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@sap.com
    - PGADMIN_DEFAULT_PASSWORD=Initial0
    # :80
    # network_mode: host
    ports:
    - 8000:80
    links:
    - postgres:postgres
    volumes:
    - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
  pgdata:
