version: "3"
services:
  pgadmin:
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@sap.com
    - PGADMIN_DEFAULT_PASSWORD=Initial0
    image: dpage/pgadmin4:3.6
    links:
    - postgres:postgres
    ports:
    - 8000:80
    volumes:
    - pgadmin:/var/lib/pgadmin
  postgres:
    environment:
    - POSTGRES_PASSWORD=Initial0
    image: postgres:11-alpine
    ports:
    - 127.0.0.1:5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgadmin: null
  pgdata: null
networks: {}
