# run cmd [ docker network create app_net ] before docker-compose up
version: '3'
services:
  nginx:
    build: .
    image: hollomyfoolish/app-proxy:1
    container_name: app-proxy
    # external_links:
    #     - app1
    #     - app2
    ports:
        - "80:80"
    networks: 
      - default
      - app_net
    volumes:
      - C:/sap-github/dockerX/proxy/nginx.conf:/etc/nginx/nginx.conf
networks: 
  app_net:
    external: true